apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    metadata:
      annotations:
        #autoscaling.knative.dev/window: "s"
        autoscaling.knative.dev/minScale: "2"
    spec:
      containers:
        - image: docker.io/hctung57/serverless-object-detection-yolo:amd-1.0.1
          ports:
            - containerPort: 8080
      #nodeSelector:
        #kubernetes.io/hostname: "cloud"
